# Generated by Django 5.0.6 on 2024-07-31 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(default=1, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.DecimalField(decimal_places=2, default=48, max_digits=10, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='archivo_pdf',
            field=models.FileField(null=True, upload_to='MEDIA/', verbose_name='PDF'),
        ),
    ]
